name: deploy to aliyun oss
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@main
    - name: delete articles
      run: rm -rf articles/*
    - name: upload files to OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: conchbrainclub
          endpoint: oss-cn-shanghai.aliyuncs.com
          folder: ./
