name: deploy to aliyun oss
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@main
      
    - name: delete articles
      run: |
        rm -rf .git
        rm -rf .github
        rm -rf articles

    - name: upgrade version
      run: sed -i "s/Conchbrain-Version/Conchbrain-$(date +%s%3N)/g" ./serviceworker.js

    - name: upload files to OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: conchbrain
          endpoint: oss-cn-shenzhen.aliyuncs.com
          folder: ./
